-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2015-10-18 11:33:39.428




-- tables
-- Table CHITIETHOADON
CREATE TABLE CHITIETHOADON (
    MA_SP int  NOT NULL,
    MA_HD int  NOT NULL,
    SO_LUONG int  NOT NULL,
    DON_GIA char(10)  NOT NULL,
    SP_MA_SP varchar(50)  NOT NULL,
    HD_MA_HD varchar(50)  NOT NULL,
    HOADON_MA_HD int  NOT NULL,
    CONSTRAINT CHITIETHOADON_pk PRIMARY KEY (MA_SP)
);

-- Table HOADON
CREATE TABLE HOADON (
    MA_HD int  NOT NULL,
    MA_KH int  NOT NULL,
    NGAY_LAPHD date  NOT NULL,
    KH_MA_KH varchar(50)  NOT NULL,
    KHACHHANG_MA_KH int  NOT NULL,
    CONSTRAINT HOADON_pk PRIMARY KEY (MA_HD)
);

-- Table HTTT
CREATE TABLE HTTT (
    ClassID int  NOT NULL,
    ClassName varchar(50)  NOT NULL,
    CONSTRAINT HTTT_pk PRIMARY KEY (ClassID)
);

-- Table KHACHHANG
CREATE TABLE KHACHHANG (
    MA_KH int  NOT NULL,
    TEN_KH varchar(50)  NOT NULL,
    PHONE int  NOT NULL,
    ADDRESS varchar(50)  NOT NULL,
    ClassID int  NOT NULL,
    HTTT_ClassID int  NOT NULL,
    CONSTRAINT KHACHHANG_pk PRIMARY KEY (MA_KH)
);

-- Table SANPHAM
CREATE TABLE SANPHAM (
    MA_SP int  NOT NULL,
    TEN_SP varchar(50)  NOT NULL,
    SO_LUONG int  NOT NULL,
    MOTA varchar(255)  NOT NULL,
    CHITIETHOADON_MA_SP int  NOT NULL,
    CONSTRAINT SANPHAM_pk PRIMARY KEY (MA_SP)
);





-- foreign keys
-- Reference:  CHITIETHOADON_HOADON (table: CHITIETHOADON)


ALTER TABLE CHITIETHOADON ADD CONSTRAINT CHITIETHOADON_HOADON FOREIGN KEY CHITIETHOADON_HOADON (HOADON_MA_HD)
    REFERENCES HOADON (MA_HD);
-- Reference:  HOADON_KHACHHANG (table: HOADON)


ALTER TABLE HOADON ADD CONSTRAINT HOADON_KHACHHANG FOREIGN KEY HOADON_KHACHHANG (KHACHHANG_MA_KH)
    REFERENCES KHACHHANG (MA_KH);
-- Reference:  KHACHHANG_HTTT (table: KHACHHANG)


ALTER TABLE KHACHHANG ADD CONSTRAINT KHACHHANG_HTTT FOREIGN KEY KHACHHANG_HTTT (HTTT_ClassID)
    REFERENCES HTTT (ClassID);
-- Reference:  SANPHAM_CHITIETHOADON (table: SANPHAM)


ALTER TABLE SANPHAM ADD CONSTRAINT SANPHAM_CHITIETHOADON FOREIGN KEY SANPHAM_CHITIETHOADON (CHITIETHOADON_MA_SP)
    REFERENCES CHITIETHOADON (MA_SP);



-- End of file.

